// react-sdk/src/components/playground/components/preview.tsx
import type { ComponentType } from "react"
import type { ConfigValue } from "../../../types/widget"
import "../styles/preview.css"

type PreviewProps = {
  Component: ComponentType<Record<string, ConfigValue>>
  configValues: Record<string, ConfigValue>
  mode?: "desktop" | "tablet" | "mobile"
}

export const Preview = ({ Component, configValues, mode = "desktop" }: PreviewProps) => {
  return (
    <div className="pg-preview-container">
      <div className={`pg-preview-window ${mode}`}>
        <div className="pg-window-header">
           <div className="pg-traffic-lights">
              <span className="pg-light pg-red"></span>
              <span className="pg-light pg-yellow"></span>
              <span className="pg-light pg-green"></span>
           </div>
           <div className="pg-address-bar">
             customer-portal.metrifox.com/billing
           </div>
           <div className="pg-window-actions">
               <div className="pg-header-icon"></div>
               <div className="pg-header-icon rounded"></div>
           </div>
        </div>
        <div className="pg-window-content">
          <Component {...configValues} />
        </div>
      </div>
    </div>
  )
}

// angular-sdk/src/components/playground/preview.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { CustomerPortalComponent, PricingTableComponent } from '@metrifox/angular-sdk';
import { EmptyStateComponent } from './empty-state.component';
import type { ConfigValue } from '../../types/widget';

@Component({
  selector: 'pg-preview',
  standalone: true,
  imports: [CommonModule, CustomerPortalComponent, PricingTableComponent, EmptyStateComponent],
  template: `
    <div class="pg-preview-container">
      <div class="pg-preview-window" [ngClass]="mode">
        <div class="pg-window-header">
          <div class="pg-traffic-lights">
            <span class="pg-light pg-red"></span>
            <span class="pg-light pg-yellow"></span>
            <span class="pg-light pg-green"></span>
          </div>
          <div class="pg-address-bar">
            customer-portal.metrifox.com/billing
          </div>
          <div class="pg-window-actions">
            <div class="pg-header-icon"></div>
            <div class="pg-header-icon rounded"></div>
          </div>
        </div>
        <div class="pg-window-content">
          @if (widgetId === 'customer-portal') {
            @if (configValues['clientKey'] && configValues['customerKey']) {
              <metrifox-customer-portal
                [customerKey]="asString(configValues['customerKey'])">
              </metrifox-customer-portal>
            } @else {
              <pg-empty-state
                title="Configuration Required"
                description="Please enter your <strong>Client Key</strong> and <strong>Customer Key</strong> in the configuration panel to render the portal.">
              </pg-empty-state>
            }
          }
          @if (widgetId === 'pricing-table') {
            @if (configValues['clientKey'] && configValues['checkoutKey'] && configValues['productKey']) {
              <metrifox-pricing-table
                [checkoutUsername]="asString(configValues['checkoutKey'])"
                [productKey]="asString(configValues['productKey'])">
              </metrifox-pricing-table>
            } @else {
              <pg-empty-state
                title="Configuration Required"
                description="Please enter your <strong>Client Key</strong>, <strong>Checkout Username</strong>, and <strong>Product Key</strong> to view the pricing table.">
              </pg-empty-state>
            }
          }
        </div>
      </div>
    </div>
  `,
})
export class PreviewComponent {
  @Input() widgetId = '';
  @Input() configValues: Record<string, ConfigValue> = {};
  @Input() mode: 'desktop' | 'tablet' | 'mobile' = 'desktop';

  asString(val: ConfigValue | undefined): string {
    return String(val ?? '');
  }
}
