// angular-sdk/src/components/playground/editable-code-view.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';
import { COPY_ICON } from './playground-icons';

@Component({
  selector: 'pg-editable-code-view',
  standalone: true,
  template: `
    <div class="pg-code-view-wrap">
      <div class="pg-code-view-header">
        <button type="button" class="pg-copy-btn" (click)="onCopy.emit()" [title]="copyLabel" [attr.aria-label]="copyLabel">
          <span [innerHTML]="copyIconHtml"></span>
          <span>{{ isCopied ? 'Copied!' : 'Copy' }}</span>
        </button>
      </div>
      <div class="pg-code-view">
        <textarea
          class="pg-code-textarea"
          [value]="value"
          (input)="onChange.emit(textareaValue($event))"
          spellcheck="false"
          [attr.aria-label]="ariaLabel">
        </textarea>
      </div>
    </div>
  `,
})
export class EditableCodeViewComponent {
  @Input() value = '';
  @Input() isCopied = false;
  @Input() copyLabel = 'Copy';
  @Input() ariaLabel = '';
  @Output() onChange = new EventEmitter<string>();
  @Output() onCopy = new EventEmitter<void>();

  copyIconHtml: SafeHtml;

  constructor(private sanitizer: DomSanitizer) {
    this.copyIconHtml = this.sanitizer.bypassSecurityTrustHtml(COPY_ICON);
  }

  textareaValue(event: Event): string {
    return (event.target as HTMLTextAreaElement).value;
  }
}

// react-sdk/src/components/playground/editable-code-view.tsx
import { CopyIcon } from "./playground-icons"

export type EditableCodeViewProps = {
  value: string
  onChange: (value: string) => void
  onCopy: () => void
  isCopied: boolean
  copyLabel: string
  ariaLabel: string
}

export const EditableCodeView = ({ value, onChange, onCopy, isCopied, copyLabel, ariaLabel }: EditableCodeViewProps) => (
  <div className="pg-code-view-wrap">
    <div className="pg-code-view-header">
      <button type="button" className="pg-copy-btn" onClick={onCopy} title={copyLabel} aria-label={copyLabel}>
        <CopyIcon />
        <span>{isCopied ? "Copied!" : "Copy"}</span>
      </button>
    </div>
    <div className="pg-code-view">
      <textarea
        className="pg-code-textarea"
        value={value}
        onChange={(e) => onChange(e.target.value)}
        spellCheck={false}
        aria-label={ariaLabel}
      />
    </div>
  </div>
)
