// angular-sdk/src/components/playground/layout.component.ts
import { Component, Input, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';
import { MetrifoxService } from '@metrifox/angular-sdk';
import type { CustomerPortalTheme } from '@metrifox/angular-sdk';
import { ConfigPanelComponent } from './config-panel.component';
import { PreviewComponent } from './preview.component';
import { ThemePanelComponent } from './theme-panel.component';
import { EditableCodeViewComponent } from './editable-code-view.component';
import { SEARCH_ICON, GITHUB_ICON } from './playground-icons';
import { TABS, PREVIEW_MODES } from './constants';
import { setNestedValue, flattenTheme } from './utils/theme-utils';
import { buildCodeSnippet } from './utils/code-snippet';
import type { WidgetDefinition, ConfigValue } from '../../types/widget';
import { THEME } from '../../types/enums';

@Component({
  selector: 'pg-layout',
  standalone: true,
  imports: [CommonModule, FormsModule, ConfigPanelComponent, PreviewComponent, ThemePanelComponent, EditableCodeViewComponent],
  template: `
    <div [class]="'pg-layout new-design pg-theme-' + themeMode">
      <!-- Sidebar -->
      <aside class="pg-sidebar-left">
        <div class="pg-sidebar-header">
          <div class="pg-logo">
            <img src="assets/metrifox-logo.png" alt="Metrifox" class="pg-logo-img">
          </div>
          <div class="pg-widget-select-wrap">
            <label for="pg-widget-select" class="pg-widget-select-label">Widget</label>
            <select id="pg-widget-select" class="pg-widget-select" [ngModel]="activeWidgetId" (ngModelChange)="selectWidget($event)">
              @for (w of widgets; track w.id) {
                <option [value]="w.id">{{ w.name }}</option>
              }
            </select>
            @if (activeWidget.description) {
              <p class="pg-widget-description">{{ activeWidget.description }}</p>
            }
          </div>
        </div>

        <div class="pg-sidebar-content">
          @if (apiConfigs.length > 0) {
            <div class="pg-config-group">
              <h3 class="pg-group-title">API Configuration</h3>
              <div class="pg-group-content">
                <pg-config-panel
                  [configs]="apiConfigs"
                  [values]="currentWidgetValues"
                  (onChange)="setWidgetConfig($event.key, $event.value)">
                </pg-config-panel>
              </div>
            </div>
          }

          <div class="pg-config-group">
            <h3 class="pg-group-title">Theme settings</h3>
            <div class="pg-theme-search-wrap">
              <span class="pg-theme-search-icon" [innerHTML]="searchIconHtml"></span>
              <input type="text" placeholder="Search theme..." [ngModel]="searchQuery" (ngModelChange)="searchQuery = $event" class="pg-theme-search-input" aria-label="Search theme">
            </div>
            <pg-theme-panel
              [theme]="activeTheme"
              [searchQuery]="searchQuery"
              [sectionDescriptions]="activeWidget.sectionDescriptions || {}"
              (themeChange)="setTheme($event.path, $event.value)">
            </pg-theme-panel>
          </div>
        </div>
      </aside>

      <!-- Main Area -->
      <main class="pg-main-area">
        <header class="pg-topbar">
          <div class="pg-tabs">
            @for (tab of tabs; track tab.id) {
              <button [class]="'pg-tab' + (activeTab === tab.id ? ' active' : '')" (click)="activeTab = tab.id">
                {{ tab.label }}
                @if (tab.badge) {
                  <span class="pg-badge">{{ tab.badge }}</span>
                }
              </button>
            }
          </div>
          <div class="pg-toolbar">
            <a [href]="activeWidget.docsUrl || 'https://docs.metrifox.com/sdks/frontend/angular'" target="_blank" rel="noopener noreferrer" class="pg-header-link">Docs</a>
            <a href="https://github.com/metrifox/metrifox-sdk-demo" target="_blank" rel="noopener noreferrer" class="pg-header-link" title="View source on GitHub">
              <span class="pg-header-link-text">View Source</span>
              <span class="pg-header-link-icon" [innerHTML]="githubIconHtml"></span>
            </a>
            <div class="pg-divider"></div>
            @for (mode of previewModes; track mode) {
              <button [class]="'pg-icon-btn' + (previewMode === mode ? ' active' : '')" (click)="previewMode = mode">
                {{ capitalize(mode) }}
              </button>
            }
            <div class="pg-divider"></div>
            <button class="pg-icon-btn" (click)="toggleTheme()">
              {{ themeMode === 'light' ? '🌙' : '☀️' }}
            </button>
          </div>
        </header>

        <div class="pg-content">
          @if (activeTab === 'preview') {
            <pg-preview
              [widgetId]="activeWidgetId"
              [configValues]="combinedValues"
              [mode]="previewMode">
            </pg-preview>
          }
          @if (activeTab === 'json') {
            <pg-editable-code-view
              [value]="jsonEditText"
              [isCopied]="copied === 'json'"
              copyLabel="Copy JSON"
              ariaLabel="JSON config"
              (onChange)="handleJsonChange($event)"
              (onCopy)="handleCopy(jsonEditText, 'json')">
            </pg-editable-code-view>
          }
          @if (activeTab === 'code') {
            <pg-editable-code-view
              [value]="codeEditText"
              [isCopied]="copied === 'code'"
              copyLabel="Copy code"
              ariaLabel="Code snippet"
              (onChange)="codeEditText = $event"
              (onCopy)="handleCopy(codeEditText, 'code')">
            </pg-editable-code-view>
          }
        </div>
      </main>
    </div>
  `,
})
export class PlaygroundLayoutComponent implements OnInit, OnDestroy {
  @Input() widgets: WidgetDefinition[] = [];

  activeWidgetId = '';
  themeMode: 'light' | 'dark' = 'light';
  activeTab: 'preview' | 'json' | 'code' = 'preview';
  previewMode: 'desktop' | 'tablet' | 'mobile' = 'desktop';
  searchQuery = '';
  copied: 'json' | 'code' | null = null;
  jsonEditText = '';
  codeEditText = '';

  tabs = TABS;
  previewModes = PREVIEW_MODES;
  searchIconHtml: SafeHtml;
  githubIconHtml: SafeHtml;

  private widgetConfigs: Record<string, Record<string, ConfigValue>> = {};
  private widgetThemeConfigs: Record<string, Record<string, unknown>> = {};
  private jsonDebounceTimer: ReturnType<typeof setTimeout> | null = null;
  private sdkInitialized = false;

  constructor(private sanitizer: DomSanitizer) {
    this.searchIconHtml = this.sanitizer.bypassSecurityTrustHtml(SEARCH_ICON);
    this.githubIconHtml = this.sanitizer.bypassSecurityTrustHtml(GITHUB_ICON);
    if (typeof window !== 'undefined' && window.matchMedia?.('(prefers-color-scheme: dark)')?.matches) {
      this.themeMode = 'dark';
    }
  }

  ngOnInit(): void {
    if (this.widgets.length > 0 && !this.activeWidgetId) {
      this.activeWidgetId = this.widgets[0].id;
    }
    this.applyThemeToDOM();
    this.initializeSDK();
  }

  ngOnDestroy(): void {
    if (this.jsonDebounceTimer) clearTimeout(this.jsonDebounceTimer);
  }

  get activeWidget(): WidgetDefinition {
    return this.widgets.find((w) => w.id === this.activeWidgetId) ?? this.widgets[0] ?? { id: '', name: '', description: '', status: 'Live' as const, docsUrl: '', highlights: [] };
  }

  get activeTheme(): Record<string, unknown> {
    return (this.widgetThemeConfigs[this.activeWidgetId] ?? this.activeWidget.defaultTheme ?? {}) as Record<string, unknown>;
  }

  get apiConfigs() {
    return this.activeWidget.configs?.filter((c) => c.section === 'api') ?? [];
  }

  get currentWidgetValues(): Record<string, ConfigValue> {
    const defaults: Record<string, ConfigValue> = {};
    this.activeWidget.configs?.forEach((c) => {
      if (c.defaultValue !== undefined) defaults[c.key] = c.defaultValue;
    });
    return { ...defaults, ...(this.widgetConfigs[this.activeWidgetId] ?? {}) };
  }

  get combinedValues(): Record<string, ConfigValue> {
    const prefix = `theme.${this.activeWidget.themeScope ?? 'customerPortal'}`;
    const flattened = flattenTheme(this.activeTheme, prefix);
    const display = this.activeTheme['display'] as Record<string, ConfigValue> | undefined;
    return { ...this.currentWidgetValues, ...flattened, ...(display ?? {}) } as Record<string, ConfigValue>;
  }

  get codeSnippet(): string {
    return buildCodeSnippet(this.activeWidgetId, this.activeWidget, this.activeTheme, this.currentWidgetValues);
  }

  selectWidget(id: string): void {
    this.activeWidgetId = id;
    this.initializeSDK();
  }

  setWidgetConfig(key: string, value: ConfigValue): void {
    this.widgetConfigs = {
      ...this.widgetConfigs,
      [this.activeWidgetId]: { ...(this.widgetConfigs[this.activeWidgetId] ?? {}), [key]: value },
    };
    if (key === 'clientKey' && value) {
      this.initializeSDK();
    }
  }

  setTheme(path: string, value: unknown): void {
    const current = { ...(this.widgetThemeConfigs[this.activeWidgetId] ?? this.activeTheme) } as Record<string, unknown>;
    this.widgetThemeConfigs = {
      ...this.widgetThemeConfigs,
      [this.activeWidgetId]: setNestedValue(current, path, value) as Record<string, unknown>,
    };
    this.applySDKTheme();
  }

  setFullTheme(theme: Record<string, unknown>): void {
    this.widgetThemeConfigs = { ...this.widgetThemeConfigs, [this.activeWidgetId]: theme };
    this.applySDKTheme();
  }

  toggleTheme(): void {
    this.themeMode = this.themeMode === THEME.LIGHT ? (THEME.DARK as 'dark') : (THEME.LIGHT as 'light');
    this.applyThemeToDOM();
  }

  capitalize(str: string): string {
    return str.charAt(0).toUpperCase() + str.slice(1);
  }

  async handleCopy(content: string, which: 'json' | 'code'): Promise<void> {
    try {
      await navigator.clipboard.writeText(content);
      this.copied = which;
      setTimeout(() => (this.copied = null), 2000);
    } catch { /* ignore */ }
  }

  handleJsonChange(value: string): void {
    this.jsonEditText = value;
    if (this.jsonDebounceTimer) clearTimeout(this.jsonDebounceTimer);
    this.jsonDebounceTimer = setTimeout(() => {
      try {
        const parsed = JSON.parse(value);
        if (parsed !== null && typeof parsed === 'object' && !Array.isArray(parsed)) {
          this.setFullTheme(parsed as Record<string, unknown>);
        }
      } catch { /* invalid JSON */ }
      this.jsonDebounceTimer = null;
    }, 500);
  }

  private applyThemeToDOM(): void {
    if (typeof document !== 'undefined') {
      const root = document.documentElement;
      root.classList.remove('light', 'dark');
      root.classList.add(this.themeMode);
      root.setAttribute('data-theme', this.themeMode);
    }
  }

  private initializeSDK(): void {
    const clientKey = this.currentWidgetValues['clientKey'] as string;
    if (!clientKey) return;
    const themeObj = this.activeTheme;
    MetrifoxService.initialize({
      clientKey,
      theme: Object.keys(themeObj).length > 0 ? { customerPortal: themeObj as CustomerPortalTheme } : undefined,
    });
    this.sdkInitialized = true;
  }

  private applySDKTheme(): void {
    if (!this.sdkInitialized) return;
    try {
      MetrifoxService.updateTheme({ customerPortal: this.activeTheme as CustomerPortalTheme });
    } catch { /* SDK may not be initialized yet */ }
  }

  private prevTab = '';
  ngDoCheck(): void {
    if (this.activeTab !== this.prevTab) {
      this.prevTab = this.activeTab;
      if (this.activeTab === 'json') {
        this.jsonEditText = JSON.stringify(this.activeTheme, null, 2);
      }
      if (this.activeTab === 'code') {
        this.codeEditText = this.codeSnippet;
      }
    }
  }
}

// react-sdk/src/components/playground/layout.tsx
import { useState, useMemo, useEffect, useRef, useCallback } from "react"
import { ConfigPanel } from "./config-panel"
import { Preview } from "./preview"
import { ThemeConfigPanel } from "./theme-panel"
import { EditableCodeView } from "./editable-code-view"
import { TABS, PREVIEW_MODES } from "./constants"
import { SearchIcon } from "./playground-icons"
import { setNestedValue, flattenTheme } from "./utils/theme-utils"
import { buildCodeSnippet } from "./utils/code-snippet"
import type { WidgetDefinition, ConfigValue } from "../../types/widget"
import metrifoxLogo from "../../assets/metrifox-logo.png"
import "./styles/playground.css"
import { THEME } from "../../types/enums"

type LayoutProps = { widgets: WidgetDefinition[] }

export const PlaygroundLayout = ({ widgets }: LayoutProps) => {
  const [activeWidgetId, setActiveWidgetId] = useState(widgets[0].id)
  const [themeMode, setThemeMode] = useState<typeof THEME.LIGHT | typeof THEME.DARK>(() =>
    typeof window !== "undefined" && window.matchMedia?.("(prefers-color-scheme: dark)")?.matches ? THEME.DARK : THEME.LIGHT,
  )
  const [activeTab, setActiveTab] = useState<"preview" | "json" | "code">("preview")
  const [previewMode, setPreviewMode] = useState<"desktop" | "tablet" | "mobile">("desktop")
  const [searchQuery, setSearchQuery] = useState("")
  const [widgetConfigs, setWidgetConfigs] = useState<Record<string, Record<string, ConfigValue>>>({})
  const [widgetThemeConfigs, setWidgetThemeConfigs] = useState<Record<string, Record<string, unknown>>>({})
  const [jsonEditText, setJsonEditText] = useState("")
  const [codeEditText, setCodeEditText] = useState("")
  const [copied, setCopied] = useState<"json" | "code" | null>(null)
  const jsonDebounceRef = useRef<ReturnType<typeof setTimeout> | null>(null)

  const activeWidget = useMemo(
    () => widgets.find((w) => w.id === activeWidgetId) ?? widgets[0],
    [widgets, activeWidgetId],
  )

  const activeTheme = useMemo(
    () => (widgetThemeConfigs[activeWidgetId] ?? activeWidget.defaultTheme ?? {}) as Record<string, unknown>,
    [widgetThemeConfigs, activeWidgetId, activeWidget.defaultTheme],
  )

  const apiConfigs = useMemo(
    () => activeWidget.configs?.filter((c) => c.section === "api") ?? [],
    [activeWidget],
  )

  const currentWidgetValues = useMemo(() => {
    const defaults: Record<string, ConfigValue> = {}
    activeWidget.configs?.forEach((config) => {
      if (config.defaultValue !== undefined) defaults[config.key] = config.defaultValue
    })
    return { ...defaults, ...(widgetConfigs[activeWidgetId] ?? {}) }
  }, [activeWidget, widgetConfigs, activeWidgetId])

  const combinedValues = useMemo((): Record<string, ConfigValue> => {
    const prefix = `theme.${activeWidget.themeScope ?? "customerPortal"}`
    const flattened = flattenTheme(activeTheme, prefix)
    const display = activeTheme.display as Record<string, ConfigValue> | undefined
    return { ...currentWidgetValues, ...flattened, ...(display ?? {}) } as Record<string, ConfigValue>
  }, [currentWidgetValues, activeTheme, activeWidget.themeScope])

  const codeSnippet = useMemo(
    () => buildCodeSnippet(activeWidgetId, activeWidget, activeTheme, currentWidgetValues),
    [activeWidgetId, activeWidget, activeTheme, currentWidgetValues],
  )

  const setFullTheme = useCallback(
    (theme: Record<string, unknown>) => {
      setWidgetThemeConfigs((prev) => ({ ...prev, [activeWidgetId]: theme }))
    },
    [activeWidgetId],
  )

  const setWidgetConfig = useCallback(
    (key: string, value: ConfigValue) => {
      setWidgetConfigs((prev) => ({
        ...prev,
        [activeWidgetId]: { ...(prev[activeWidgetId] ?? {}), [key]: value },
      }))
    },
    [activeWidgetId],
  )

  const setTheme = useCallback(
    (path: string, value: unknown) => {
      setWidgetThemeConfigs((prev) => ({
        ...prev,
        [activeWidgetId]: setNestedValue(
          { ...(prev[activeWidgetId] ?? activeTheme) } as Record<string, unknown>,
          path,
          value,
        ) as Record<string, unknown>,
      }))
    },
    [activeWidgetId, activeTheme],
  )

  const handleCopy = useCallback(async (content: string, which: "json" | "code") => {
    try {
      await navigator.clipboard.writeText(content)
      setCopied(which)
      setTimeout(() => setCopied(null), 2000)
    } catch {
      // ignore
    }
  }, [])

  const handleJsonChange = useCallback(
    (value: string) => {
      setJsonEditText(value)
      if (jsonDebounceRef.current) clearTimeout(jsonDebounceRef.current)
      jsonDebounceRef.current = setTimeout(() => {
        try {
          const parsed = JSON.parse(value) as unknown
          if (parsed !== null && typeof parsed === "object" && !Array.isArray(parsed)) {
            setFullTheme(parsed as Record<string, unknown>)
          }
        } catch {
          // invalid JSON
        }
        jsonDebounceRef.current = null
      }, 500)
    },
    [setFullTheme],
  )

  useEffect(() => {
    if (activeTab === "json") {
      const next = JSON.stringify(activeTheme, null, 2)
      queueMicrotask(() => setJsonEditText(next))
    }
    if (activeTab === "code") {
      queueMicrotask(() => setCodeEditText(codeSnippet))
    }
  }, [activeTab, activeTheme, codeSnippet])

  useEffect(() => {
    const root = document.documentElement
    root.classList.remove("light", "dark")
    root.classList.add(themeMode)
    root.setAttribute("data-theme", themeMode)
  }, [themeMode])

  return (
    <div className={`pg-layout new-design pg-theme-${themeMode}`}>
      <aside className="pg-sidebar-left">
        <div className="pg-sidebar-header">
          <div className="pg-logo">
            <img src={metrifoxLogo} alt="Metrifox" className="pg-logo-img" />
          </div>
          <div className="pg-widget-select-wrap">
            <label htmlFor="pg-widget-select" className="pg-widget-select-label">Widget</label>
            <select
              id="pg-widget-select"
              className="pg-widget-select"
              value={activeWidgetId}
              onChange={(e) => setActiveWidgetId(e.target.value)}
            >
              {widgets.map((w) => (
                <option key={w.id} value={w.id}>{w.name}</option>
              ))}
            </select>
            {activeWidget.description && <p className="pg-widget-description">{activeWidget.description}</p>}
          </div>
        </div>

        <div className="pg-sidebar-content">
          {apiConfigs.length > 0 && (
            <div className="pg-config-group">
              <h3 className="pg-group-title">API Configuration</h3>
              <div className="pg-group-content">
                <ConfigPanel configs={apiConfigs} values={currentWidgetValues} onChange={setWidgetConfig} />
              </div>
            </div>
          )}

          <div className="pg-config-group">
            <h3 className="pg-group-title">Theme settings</h3>
            <div className="pg-theme-search-wrap">
              <SearchIcon />
              <input
                type="text"
                placeholder="Search theme..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="pg-theme-search-input"
                aria-label="Search theme"
              />
            </div>
            <ThemeConfigPanel
              theme={activeTheme}
              onChange={setTheme}
              searchQuery={searchQuery}
              sectionDescriptions={activeWidget.sectionDescriptions}
            />
          </div>
        </div>
      </aside>

      <main className="pg-main-area">
        <header className="pg-topbar">
          <div className="pg-tabs">
            {TABS.map((tab) => (
              <button
                key={tab.id}
                className={`pg-tab ${activeTab === tab.id ? "active" : ""}`}
                onClick={() => setActiveTab(tab.id)}
              >
                {tab.label}
                {tab.badge && <span className="pg-badge">{tab.badge}</span>}
              </button>
            ))}
          </div>
          <div className="pg-toolbar">
            <a href={activeWidget.docsUrl ?? "https://docs.metrifox.com/sdks/frontend/react"} target="_blank" rel="noopener noreferrer" className="pg-header-link">Docs</a>
            <a href="https://github.com/metrifox/metrifox-sdk-demo" target="_blank" rel="noopener noreferrer" className="pg-header-link" title="View source on GitHub">
              <span className="pg-header-link-text">View Source</span>
              <svg className="pg-header-link-icon" width="16" height="16" viewBox="0 0 16 16" fill="currentColor" aria-hidden>
                <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0016 8c0-4.42-3.58-8-8-8z" />
              </svg>
            </a>
            <div className="pg-divider" />
            {PREVIEW_MODES.map((mode) => (
              <button
                key={mode}
                className={`pg-icon-btn ${previewMode === mode ? "active" : ""}`}
                onClick={() => setPreviewMode(mode)}
              >
                {mode.charAt(0).toUpperCase() + mode.slice(1)}
              </button>
            ))}
            <div className="pg-divider" />
            <button className="pg-icon-btn" onClick={() => setThemeMode((p) => (p === THEME.LIGHT ? THEME.DARK : THEME.LIGHT))}>
              {themeMode === "light" ? "🌙" : "☀️"}
            </button>
          </div>
        </header>

        <div className="pg-content">
          {activeTab === "preview" && (
            <Preview Component={activeWidget.component} configValues={combinedValues} mode={previewMode} />
          )}
          {activeTab === "json" && (
            <EditableCodeView
              value={jsonEditText}
              onChange={handleJsonChange}
              onCopy={() => handleCopy(jsonEditText, "json")}
              isCopied={copied === "json"}
              copyLabel="Copy JSON"
              ariaLabel="JSON config"
            />
          )}
          {activeTab === "code" && (
            <EditableCodeView
              value={codeEditText}
              onChange={setCodeEditText}
              onCopy={() => handleCopy(codeEditText, "code")}
              isCopied={copied === "code"}
              copyLabel="Copy code"
              ariaLabel="Code snippet"
            />
          )}
        </div>
      </main>
    </div>
  )
}
