// angular-sdk/src/components/playground/theme-panel.component.ts
import { Component, Input, Output, EventEmitter, Pipe, PipeTransform } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

@Pipe({ name: 'formatLabel', standalone: true })
export class FormatLabelPipe implements PipeTransform {
  transform(key: string): string {
    return key.replace(/([A-Z])/g, ' $1').replace(/^./, (s) => s.toUpperCase());
  }
}

@Component({
  selector: 'pg-theme-panel',
  standalone: true,
  imports: [CommonModule, FormsModule, FormatLabelPipe],
  template: `
    @for (sectionKey of visibleSections; track sectionKey) {
      <div class="tp-root-section">
        <button class="tp-root-header" (click)="toggleRootSection(sectionKey)">
          <h3 class="tp-root-title">{{ sectionKey | formatLabel }}</h3>
          <span class="tp-chevron" [class.open]="isRootOpen(sectionKey)">›</span>
        </button>
        @if (sectionDescriptions[sectionKey]) {
          <p class="tp-root-description">{{ sectionDescriptions[sectionKey] }}</p>
        }
        @if (isRootOpen(sectionKey)) {
          <div class="tp-root-content">
            <ng-container *ngTemplateOutlet="recursiveGroup; context: { $implicit: getThemeSection(sectionKey), path: sectionKey, level: 0 }"></ng-container>
          </div>
        }
      </div>
    }

    <ng-template #recursiveGroup let-data let-path="path" let-level="level">
      <div [class]="'tp-group level-' + level">
        @for (entry of objectEntries(data); track entry[0]) {
          @if (isObject(entry[1])) {
            <div class="tp-section">
              <button type="button" class="tp-section-header" (click)="toggleSection(path + '.' + entry[0])"
                [style.paddingLeft.px]="level > 0 ? 8 : 0">
                <span class="tp-section-title">{{ entry[0] | formatLabel }}</span>
                <span class="tp-chevron" [class.open]="isSectionOpen(path + '.' + entry[0])">›</span>
              </button>
              @if (isSectionOpen(path + '.' + entry[0])) {
                <div class="tp-section-content">
                  <ng-container *ngTemplateOutlet="recursiveGroup; context: { $implicit: entry[1], path: path + '.' + entry[0], level: level + 1 }"></ng-container>
                </div>
              }
            </div>
          } @else {
            <div class="tp-config-item">
              <label class="tp-label">{{ entry[0] | formatLabel }}</label>
              @if (isBooleanValue(entry[1])) {
                <label class="tp-toggle">
                  <input type="checkbox" [checked]="entry[1] === true"
                    (change)="emitChange(path + '.' + entry[0], asCheckbox($event))">
                  <span>{{ entry[1] === true ? 'On' : 'Off' }}</span>
                </label>
              } @else if (isColorValue(entry[0], entry[1])) {
                <div class="tp-color-input">
                  <div class="tp-color-swatch-wrapper">
                    <input type="color" [value]="asString(entry[1])" (input)="emitChange(path + '.' + entry[0], inputValue($event))" class="tp-color-swatch">
                    <div class="tp-color-preview" [style.backgroundColor]="asString(entry[1])"></div>
                  </div>
                  <input type="text" [value]="asString(entry[1])" (input)="emitChange(path + '.' + entry[0], inputValue($event))" class="tp-text-input tp-color-text">
                </div>
              } @else if (isSliderValue(entry[0])) {
                <div class="tp-slider-input">
                  <input type="range" min="0" max="32" [value]="parseNumeric(entry[1])"
                    (input)="emitChange(path + '.' + entry[0], inputValue($event) + 'px')" class="tp-range">
                  <input type="text" [value]="asString(entry[1])"
                    (input)="emitChange(path + '.' + entry[0], inputValue($event))" class="tp-text-input tp-slider-text">
                </div>
              } @else {
                <input type="text" [value]="asString(entry[1])"
                  (input)="emitChange(path + '.' + entry[0], inputValue($event))" class="tp-text-input">
              }
              @if (entry[0] === 'fontFamily') {
                <span class="tp-field-hint">Inherits from the host app by default. Pass any font-family string to override and ensure the font is loaded in your app.</span>
              }
            </div>
          }
        }
      </div>
    </ng-template>
  `,
})
export class ThemePanelComponent {
  @Input() theme: Record<string, unknown> = {};
  @Input() searchQuery = '';
  @Input() sectionDescriptions: Record<string, string> = {};
  @Output() themeChange = new EventEmitter<{ path: string; value: unknown }>();

  private openRootSections = new Set<string>();
  private openSections = new Set<string>();

  get visibleSections(): string[] {
    const sections = Object.keys(this.theme);
    const q = this.searchQuery.trim().toLowerCase();
    return q ? sections.filter((s) => s.toLowerCase().includes(q)) : sections;
  }

  getThemeSection(key: string): Record<string, unknown> {
    return (this.theme[key] ?? {}) as Record<string, unknown>;
  }

  isRootOpen(key: string): boolean {
    if (this.searchQuery.trim()) return true;
    return !this.openRootSections.has(key + '__closed');
  }

  toggleRootSection(key: string): void {
    const closedKey = key + '__closed';
    if (this.openRootSections.has(closedKey)) {
      this.openRootSections.delete(closedKey);
    } else {
      this.openRootSections.add(closedKey);
    }
  }

  isSectionOpen(path: string): boolean {
    return !this.openSections.has(path + '__closed');
  }

  toggleSection(path: string): void {
    const closedKey = path + '__closed';
    if (this.openSections.has(closedKey)) {
      this.openSections.delete(closedKey);
    } else {
      this.openSections.add(closedKey);
    }
  }

  objectEntries(obj: unknown): [string, unknown][] {
    if (typeof obj !== 'object' || obj === null) return [];
    return Object.entries(obj);
  }

  isObject(val: unknown): boolean {
    return typeof val === 'object' && val !== null && !Array.isArray(val);
  }

  isBooleanValue(val: unknown): boolean {
    return typeof val === 'boolean';
  }

  isColorValue(key: string, val: unknown): boolean {
    const s = String(val ?? '');
    return s.startsWith('#') || s.startsWith('rgb') ||
      key.toLowerCase().includes('color') || key.toLowerCase().includes('background');
  }

  isSliderValue(key: string): boolean {
    return key.toLowerCase().includes('radius') || key.toLowerCase().includes('padding') || key.toLowerCase().includes('gap');
  }

  asString(val: unknown): string {
    return typeof val === 'string' ? val : String(val ?? '');
  }

  parseNumeric(val: unknown): number {
    return parseInt(String(val ?? '0').replace(/[^0-9]/g, ''), 10) || 0;
  }

  inputValue(event: Event): string {
    return (event.target as HTMLInputElement).value;
  }

  asCheckbox(event: Event): boolean {
    return (event.target as HTMLInputElement).checked;
  }

  emitChange(path: string, value: unknown): void {
    this.themeChange.emit({ path, value });
  }
}

// react-sdk/src/components/playground/theme-panel.tsx
import { useState, type ChangeEvent, useEffect } from "react"
import "./styles/theme-panel.css"

type ThemeConfigPanelProps = {
  theme: Record<string, unknown>
  onChange: (path: string, value: unknown) => void
  searchQuery?: string
  sectionDescriptions?: Record<string, string>
}

const formatLabel = (key: string) => {
  return key
    .replace(/([A-Z])/g, " $1")
    .replace(/^./, (str) => str.toUpperCase())
}

const ColorInput = ({
  value,
  onChange,
}: {
  value: string
  onChange: (val: string) => void
}) => {
  const [localValue, setLocalValue] = useState(value)

  useEffect(() => {
    setLocalValue(value)
  }, [value])

  const handleChange = (e: ChangeEvent<HTMLInputElement>) => {
    setLocalValue(e.target.value)
    onChange(e.target.value)
  }

  return (
    <div className="tp-color-input">
      <div className="tp-color-swatch-wrapper">
        <input
          type="color"
          value={localValue}
          onChange={handleChange}
          className="tp-color-swatch"
        />
        <div
          className="tp-color-preview"
          style={{ backgroundColor: localValue }}
        />
      </div>
      <input
        type="text"
        value={localValue}
        onChange={handleChange}
        className="tp-text-input tp-color-text"
      />
    </div>
  )
}

const SliderInput = ({
  value,
  onChange,
  unit = "px",
}: {
  value: string
  onChange: (val: string) => void
  unit?: string
}) => {
  const numericValue = parseInt(value.replace(unit, ""), 10) || 0

  const handleSliderChange = (e: ChangeEvent<HTMLInputElement>) => {
    onChange(`${e.target.value}${unit}`)
  }

  const handleTextChange = (e: ChangeEvent<HTMLInputElement>) => {
    onChange(e.target.value)
  }

  return (
    <div className="tp-slider-input">
      <input
        type="range"
        min="0"
        max="32"
        value={numericValue}
        onChange={handleSliderChange}
        className="tp-range"
      />
      <input
        type="text"
        value={value}
        onChange={handleTextChange}
        className="tp-text-input tp-slider-text"
      />
    </div>
  )
}

const ConfigItem = ({
  label,
  value,
  onChange,
  itemKey,
}: {
  label: string
  value: unknown
  onChange: (val: unknown) => void
  itemKey: string
}) => {
  const strValue = typeof value === "string" ? value : String(value ?? "")
  const isBoolean = typeof value === "boolean"
  const isColor =
    (typeof value === "string" && value.startsWith("#")) ||
    (typeof value === "string" && value.startsWith("rgb")) ||
    label.toLowerCase().includes("color") ||
    label.toLowerCase().includes("background")

  const isBorderRadius = itemKey.toLowerCase().includes("radius")
  const isSpacing = itemKey.toLowerCase().includes("padding") || itemKey.toLowerCase().includes("gap")
  const isFontFamily = itemKey === "fontFamily"

  return (
    <div className="tp-config-item">
      <label className="tp-label">{label}</label>
      {isBoolean ? (
        <label className="tp-toggle">
          <input
            type="checkbox"
            checked={value === true}
            onChange={(e) => onChange(e.target.checked)}
          />
          <span>{value === true ? "On" : "Off"}</span>
        </label>
      ) : isColor ? (
        <ColorInput value={strValue} onChange={(val) => onChange(val)} />
      ) : isBorderRadius || isSpacing ? (
        <SliderInput value={strValue} onChange={(val) => onChange(val)} />
      ) : (
        <input
          type="text"
          value={strValue}
          onChange={(e) => onChange(e.target.value)}
          className="tp-text-input"
        />
      )}
      {isFontFamily && (
        <span className="tp-field-hint">
          Inherits from the host app by default. Pass any font-family string to override and ensure the font is loaded in your app.
        </span>
      )}
    </div>
  )
}

const CollapsibleRootSection = ({
  title,
  description,
  children,
  searchQuery,
}: {
  title: string
  description?: string
  children: React.ReactNode
  searchQuery: string
}) => {
  const [isOpen, setIsOpen] = useState(true)
  const effectiveOpen = searchQuery.trim() ? true : isOpen

  return (
    <div className="tp-root-section">
      <button className="tp-root-header" onClick={() => setIsOpen(!isOpen)}>
        <h3 className="tp-root-title">{title}</h3>
        <span className={`tp-chevron ${effectiveOpen ? "open" : ""}`}>›</span>
      </button>
      {description && <p className="tp-root-description">{description}</p>}
      {effectiveOpen && <div className="tp-root-content">{children}</div>}
    </div>
  )
}

const CollapsibleSection = ({
  label,
  level,
  children,
}: {
  label: string
  level: number
  children: React.ReactNode
}) => {
  const [isOpen, setIsOpen] = useState(true)

  return (
    <div className="tp-section">
      <button
        type="button"
        className="tp-section-header"
        onClick={() => setIsOpen((prev) => !prev)}
        style={{ paddingLeft: level > 0 ? 8 : 0 }}
      >
        <span className="tp-section-title">{label}</span>
        <span className={`tp-chevron ${isOpen ? "open" : ""}`}>›</span>
      </button>
      {isOpen && <div className="tp-section-content">{children}</div>}
    </div>
  )
}

const RecursiveGroup = ({
  data,
  path,
  onChange,
  level = 0,
}: {
  data: Record<string, unknown>
  path: string
  onChange: (path: string, val: unknown) => void
  level?: number
}) => {
  if (typeof data !== "object" || data === null) {
    return null
  }

  const entries = Object.entries(data)

  return (
    <div className={`tp-group level-${level}`}>
      {entries.map(([key, value]) => {
        const currentPath = path ? `${path}.${key}` : key
        const isObject =
          typeof value === "object" && value !== null && !Array.isArray(value)
        const label = formatLabel(key)

        if (isObject) {
          return (
            <CollapsibleSection key={key} label={label} level={level}>
              <RecursiveGroup
                data={value as Record<string, unknown>}
                path={currentPath}
                onChange={onChange}
                level={level + 1}
              />
            </CollapsibleSection>
          )
        }

        return (
          <ConfigItem
            key={key}
            itemKey={key}
            label={label}
            value={value}
            onChange={(val) => onChange(currentPath, val)}
          />
        )
      })}
    </div>
  )
}

export const ThemeConfigPanel = ({
  theme,
  onChange,
  searchQuery = "",
  sectionDescriptions,
}: ThemeConfigPanelProps) => {
  const sections = Object.keys(theme)
  const q = searchQuery.trim().toLowerCase()

  const visibleSections = q
    ? sections.filter((sectionKey) => sectionKey.toLowerCase().includes(q))
    : sections

  return (
    <div className="tp-panel">
      {visibleSections.map((sectionKey) => (
        <CollapsibleRootSection
          key={sectionKey}
          title={formatLabel(sectionKey)}
          description={sectionDescriptions?.[sectionKey]}
          searchQuery={searchQuery}
        >
          <RecursiveGroup
            data={(theme[sectionKey] ?? {}) as Record<string, unknown>}
            path={sectionKey}
            onChange={onChange}
            level={0}
          />
        </CollapsibleRootSection>
      ))}
    </div>
  )
}
